Metrics web
prolajumokeoni/metrics-web pull request #1
Opened 2021-10-14 12:46 UTC by prolajumokeoni

In this project:
- Selected the Jason placeholder API
- Built files structure  app
- Created routes and navigation 
- Created unit and integration tests
- Sorted posts  alphabetically by titles
### Video link: https://www.loom.com/share/51aba3bff9704b02a0561587327a7fd6

2021-10-14 13:21 UTC, mke2111 requested changes
### Hey @prolajumokeoni, 

**This is a great project you have going on, well-done lad**. 

   
**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

## Required Changes ♻️

- [x] Add the testing command to the readme file (set up section)

_Check the inline comments under the review for sections to improve._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-14 13:28 UTC, mke2111 commented on src/components/Posts.js
> +};
- [ ] The Home page has list of categories that could be filtered using given parameters, e.g. category name.

2021-10-14 13:37 UTC, mke2111 commented on src/components/SinglePost.js
> +      </NavLink>
- [ ] Following the given design specs is one of the best practices clients would like. The layout of the `back` element is not as given in the design specs. Give this a fix. 😄
![Screenshot from 2021-10-14 16-36-30](https://user-images.githubusercontent.com/65501535/137328387-717d3fae-068c-4d25-94ae-fe67d10ec732.png)
![Screenshot from 2021-10-14 16-37-18](https://user-images.githubusercontent.com/65501535/137328552-26569cb0-0d53-4d4e-9a29-fa1261f09c25.png)

2021-10-14 15:42 UTC, prolajumokeoni commented on src/components/Posts.js
> +};
Thank you for your review @mke2111, I have implemented the changes

2021-10-15 01:09 UTC, mke2111 approved these changes
### Hi @prolajumokeoni, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
**Congratulations! 🎉** 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-15 02:31 UTC, merged